In [1]:
import pandas as pd
import numpy as np

#Python SQLITE数据库是一款非常小巧的嵌入式开源数据库软件
import sqlite3

In [2]:
triplet_dataset = pd.read_csv('train.csv', nrows=5000000)

In [3]:
triplet_dataset.head(n=10)

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1.000009e+18,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,1.000017e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,1.000037e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,1.000064e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,1.000068e+19,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157
5,1.000072e+19,0,14102100,1005,0,d6137915,bb1ef334,f028772b,ecad2386,7801e8d9,...,1,0,16920,320,50,1899,0,431,100077,117
6,1.000072e+19,0,14102100,1005,0,8fda644b,25d4cfcd,f028772b,ecad2386,7801e8d9,...,1,0,20362,320,50,2333,0,39,-1,157
7,1.000092e+19,0,14102100,1005,1,e151e245,7e091613,f028772b,ecad2386,7801e8d9,...,1,0,20632,320,50,2374,3,39,-1,23
8,1.000095e+19,1,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15707,320,50,1722,0,35,-1,79
9,1.000126e+19,0,14102100,1002,0,84c7ba46,c4e18dd6,50e219e0,ecad2386,7801e8d9,...,0,0,21689,320,50,2496,3,167,100191,23

In [4]:
triplet_dataset.to_csv('sub_train.csv', index = False)

In [5]:
EF_dataset = pd.read_csv('FE_train.csv', nrows=10000000)

In [6]:
EF_dataset.head(n = 10)

,click,C1_1001,C1_1002,C1_1005,C1_1007,C1_1008,C1_1010,C1_1012,banner_pos_0,banner_pos_1,...,C15_C16_-160,C15_C16_50,C15_C16_100,C15_C16_160,C15_C16_180,C15_C16_250,C15_C16_256,C15_C16_270,C15_C16_638,weekday
0,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1
1,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1
2,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1
3,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1
4,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,1
5,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1
6,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1
7,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,1
8,1,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1
9,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1

In [3]:
dataset = pd.read_csv('sub_train.csv', nrows=1000)

In [5]:
dataset['hour']

0      14102100
1      14102100
2      14102100
3      14102100
4      14102100
5      14102100
6      14102100
7      14102100
8      14102100
9      14102100
10     14102100
11     14102100
12     14102100
13     14102100
14     14102100
15     14102100
16     14102100
17     14102100
18     14102100
19     14102100
20     14102100
21     14102100
22     14102100
23     14102100
24     14102100
25     14102100
26     14102100
27     14102100
28     14102100
29     14102100
         ...
970    14102100
971    14102100
972    14102100
973    14102100
974    14102100
975    14102100
976    14102100
977    14102100
978    14102100
979    14102100
980    14102100
981    14102100
982    14102100
983    14102100
984    14102100
985    14102100
986    14102100
987    14102100
988    14102100
989    14102100
990    14102100
991    14102100
992    14102100
993    14102100
994    14102100
995    14102100
996    14102100
997    14102100
998    14102100
999    14102100
Name: hour, Length: 1000, dtype: int64

In [5]:
triplet_dataset_test = pd.read_csv('test.csv', nrows=5000000)

In [6]:
triplet_dataset_test.to_csv('sub_test.csv', index = False)